
  CREATE TABLE "SYS"."MUSTERILER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MUSTERI_ADI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MUSTERI_SOYADI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DOGUMTARIHI" DATE, 
	"ADRES" VARCHAR2(250 BYTE), 
	"MUS_SALON_ID" NUMBER(*,0), 
	"MUS_OG_ID" NUMBER(*,0), 
	 CONSTRAINT "MUSTERILER_PK" PRIMARY KEY ("ID"),
  	 CONSTRAINT "MUSTERILER_FK1" FOREIGN KEY ("MUS_SALON_ID")
	  REFERENCES "SYS"."SALONLAR" ("SALON_ID") ENABLE, 
	 CONSTRAINT "MUSTERILER_FK2" FOREIGN KEY ("MUS_OG_ID")
	  REFERENCES "SYS"."OGRETMENLER" ("OG_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ;


  CREATE TABLE "SYS"."SALONLAR" 
   (	"SALON_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SALON_ADI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SALON_ÖÐRETMEN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SALON_BÖLGE" VARCHAR2(20 BYTE), 
	"SALON_DERSSAATÝ" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "SALONLAR_PK" PRIMARY KEY ("SALON_ID")
   );
  
  
  CREATE TABLE "SYS"."OGRETMENLER" 
   (	"OG_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"OG_ADI_SOYADI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"	"OG_ADRES" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OG_BOLUM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OG_DERSSAATI" TIMESTAMP (6) NOT NULL ENABLE, 
	"OG_CESÝDÝ" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "OGRETMENLER_PK" PRIMARY KEY ("OG_ID")
  
   );


  
  
  
